baseURL = 'http://andreseponce.com/'
languageCode = 'en-us'
title = 'Andrés Ponce'
theme = 'mainroad'

# Mainroad
paginate = 1

[Author]
	name = 'Andrés Ponce'
	bio = 'Hondruan graduate student in Taiwan. '
	avatar = "/me.jpg"

[Params]
	copyright = 'Andrés Ponce'
	mathjax = true
  	mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
  	mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  	googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700" # Load Google Fonts
	pager=true

[Params.style.vars]
  highlightColor = "#e22d30" # Override highlight color

  # Override font-family sets
  # Take care of different quotes OR escaping symbols in these params if necessary
  fontFamilyPrimary = "Georgia, Lucinda, serif"
[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["categories", "recent", 'social']
  # alternatively "ddg-search" can be used, to search via DuckDuckGo
  # widgets = ["ddg-search", "recent", "categories", "taglist", "social", "languages

[Params.widgets.social]
	email = 'andreseeponce@gmail.com'
# Tale
[menu]
	[[menu.main]]
		identifier = "Posts"
		name = "Posts"
		title = "Posts"
		url = '/posts/'
